name: Node.js Package

on:
  push:
    branches:
      - main
    paths:
      - index.js
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -R
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Install dependencies
        run: npm install

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
        
      - name: Install dependencies
        run: npm install
        
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
