name: Node.js Package

on:
  push:
    branches:
      - main
    paths:
      - index.js
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history

      - name: Print working directory
        run: pwd

      - name: List files in the root directory
        run: ls -la

      - name: List files recursively
        run: ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Navigate to the project directory
        run: cd internship_assignment_node_project  # Navigate to the correct directory
        
      - name: Install dependencies
        run: npm install
        working-directory: internship_assignment_node_project  # Set the working directory for npm install

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
        
      - name: Install dependencies
        run: npm install
        working-directory: internship_assignment_node_project  # Set the working directory for npm install
        
      - name: Publish package
        run: npm publish
        working-directory: internship_assignment_node_project  # Set the working directory for npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
